import 'bootstrap/dist/css/bootstrap.min.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono, Antic_Didone } from 'next/font/google'
import { Toaster } from '../components/ui/sonner'
import './globals.css'

const anticDidone = Antic_Didone({
  variable: '--font-antic-didone',
  subsets: ['latin'],
  weight: '400',
})
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'LITRATOBYAM',
  description: 'Generated by create next app',
  icons: {
    icon: '/Icons/litratoicon.png',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${anticDidone.variable} select-none antialiased`}
      >
        {children}
        {/* Global toast notifications */}
        <Toaster richColors position="top-center" />
      </body>
    </html>
  )
}
